export const PREVIEW_REQUEST = 'RESULTS__PREVIEW_REQUEST';
export const PREVIEW_SUCCESS = 'RESULTS__PREVIEW_SUCCESS';
export const PREVIEW_FAILED = 'RESULTS__PREVIEW_FAILED';
export const PREVIEW_CANCELED = 'RESULTS__PREVIEW_CANCELED';
