export const SEARCH_REQUEST = 'BOOKS__SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'BOOKS__SEARCH_SUCCESS';
export const SEARCH_FAILED = 'BOOKS__SEARCH_FAILED';
export const SEARCH_CANCELED = 'BOOKS__SEARCH_CANCELED';
