export const SETTINGS_UPDATE = 'SETTINGS__UPDATE';

export const SETTINGS_LOAD_REQUEST = 'SETTINGS__LOAD_REQUEST';
export const SETTINGS_LOAD_SUCCESS = 'SETTINGS__LOAD_SUCCESS';
export const SETTINGS_LOAD_FAILED = 'SETTINGS__LOAD_FAILED';
